import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import "../style/main.css";
import "../style/extra.css";

import Header from "../components/common/Header";

const poppins = Poppins({
  weight: "500",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface MenuItem {
  label: string;
  url: string;
  dropdown?: boolean;
  dropdownItems?: MenuItem[];
}

const menuData: MenuItem[] = [
  { label: "Home", url: "/" },
  {
    label: "Ipo",
    url: "",
    dropdown: true,
    dropdownItems: [
      { label: "Upcoming", url: "/about" },
      { label: "GreyMarket", url: "/team" },
    ],
  },
  {
    label: "Calculators",
    url: "",
    dropdown: true,
    dropdownItems: [
      { label: "Sip Calculator", url: "/about" },
      { label: "Lumpsum Calculator", url: "/team" },
    ],
  },
  {
    label: "Mutual Funds",
    url: "/",
    // dropdown: true,
    // dropdownItems: [
    //   { label: "About", url: "/about" },
    //   { label: "Team", url: "/team" },
    //   { label: "How It Works", url: "/how-it-works" },
    //   { label: "Career", url: "/careers" },
    // ],
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header menuData={menuData ?? []} />
        {children}
      </body>
    </html>
  );
}
